#ifndef __COMMAND_CTRL_H
 #define __COMMAND_CTRL_H

#define API_CMD_LEN             13
#define API_LOT_VER_LEN         10
#define API_T1_CUTOFF_LEN       6
#define API_T2_CUTOFF_LEN       4
#define API_T3_CUTOFF_LEN       4
#define BLE_NAME_BUF_SIZE       21

typedef enum
{
	CMD_NONE = 0,
	CMD_PRODUCT_MODE_START = 1,
	CMD_CALIBRATION_STICK_CHECK,
	CMD_CALIBRATION_START,
	CMD_CALIBRATION_STATE_CHECK,
	CMD_CALIBRATION_RESULT,
	CMD_PREG_CUTOFF_SETTING,
	CMD_OVUL_CUTOFF_SETTING,
	CMD_MENO_CUTOFF_SETTING,
	CMD_REACT_TIME_SETTING,
	CMD_CORRECTION_FACTOR_SETTING,
	CMD_BLE_NAME_SETUP_PASS,
	CMD_BLE_NAME_SETUP_START,
	CMD_QA_STICK_CHECK,
	CMD_QA_START,
	CMD_QA_DOING,
	CMD_QA_RESULT,
	CMD_PRODUCT_MODE_END,
	CMD_FW_UPD_ENTER_IAP_MODE,
	CMD_FW_UPD_START_MODE,
	CMD_FW_UPD_DATA_TRANSMIT_MODE,
	CMD_FW_UPD_END_MODE,
	CMD_READ_PTR,
	CMD_READ_PTR_END
}RX_MSG_FUNCTION_Typedef;

typedef enum
{
	MSG_NONE = 0,
	NORMAL_MESSAGE = 1,
	ERROR_RETRY_MESSAGE,
	ERROR_LENGTH_MISMATCH,
	ERROR_UNIDENTIFIED_CMD,
	ERROR_INCORRECT_VALUE,
    PACKET_DATA_ACK,
    PACKET_DATA_NACK,
	MSG_WAITING
}RX_MSG_CHECK_Typedef;

void API_Rx_Command_Process();
void API_Tx_Command_Process(char cmd_name);
int str_to_dec(char *str, int len);
void u_strncpy(char *dest_buf, char *buf, int size);

#endif /* __COMMAND_CTRL_H*/  
