#include "main.h"

 

void Get_BLE_Name(int panel)
{
	GetCtrlVal (panel, SUB_PANEL_sINDI_BLE_NAME, DATA_BANK.BLE_NAME_STR);	   
}

void Get_Standard_Stick_Data(int panel)
{
/*    
    GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH1, &DATA_BANK.QA_STD_STICK_RAW_DATA[1]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH2, &DATA_BANK.QA_STD_STICK_RAW_DATA[2]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH3, &DATA_BANK.QA_STD_STICK_RAW_DATA[3]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH4, &DATA_BANK.QA_STD_STICK_RAW_DATA[4]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH5, &DATA_BANK.QA_STD_STICK_RAW_DATA[5]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH6, &DATA_BANK.QA_STD_STICK_RAW_DATA[6]); 
	GetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH7, &DATA_BANK.QA_STD_STICK_RAW_DATA[7]);
*/
}

void Get_Standard_Stick_Tolerance_Data(int panel)
{
/*    
    GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH1, &DATA_BANK.QA_TOLERANCE_DATA[1]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH2, &DATA_BANK.QA_TOLERANCE_DATA[2]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH3, &DATA_BANK.QA_TOLERANCE_DATA[3]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH4, &DATA_BANK.QA_TOLERANCE_DATA[4]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH5, &DATA_BANK.QA_TOLERANCE_DATA[5]);
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH6, &DATA_BANK.QA_TOLERANCE_DATA[6]); 
	GetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH7, &DATA_BANK.QA_TOLERANCE_DATA[7]);
*/
}



void Set_Standard_Stick_Data(int panel)
{
/*    
    SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH1, DATA_BANK.QA_STD_STICK_RAW_DATA[1]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH2, DATA_BANK.QA_STD_STICK_RAW_DATA[2]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH3, DATA_BANK.QA_STD_STICK_RAW_DATA[3]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH4, DATA_BANK.QA_STD_STICK_RAW_DATA[4]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH5, DATA_BANK.QA_STD_STICK_RAW_DATA[5]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH6, DATA_BANK.QA_STD_STICK_RAW_DATA[6]); 
	SetCtrlVal (panel, TABPANEL_6_INPUT_STD_S_DATA_CH7, DATA_BANK.QA_STD_STICK_RAW_DATA[7]);
*/
}

void Set_Standard_Stick_Tolerance_Data(int panel)
{
/*    
    SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH1, DATA_BANK.QA_TOLERANCE_DATA[1]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH2, DATA_BANK.QA_TOLERANCE_DATA[2]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH3, DATA_BANK.QA_TOLERANCE_DATA[3]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH4, DATA_BANK.QA_TOLERANCE_DATA[4]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH5, DATA_BANK.QA_TOLERANCE_DATA[5]);
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH6, DATA_BANK.QA_TOLERANCE_DATA[6]); 
	SetCtrlVal (panel, TABPANEL_6_INPUT_TOL_DATA_CH7, DATA_BANK.QA_TOLERANCE_DATA[7]);
*/
}
